[package]
name = "ellama"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
catppuccin-egui = { git = "https://github.com/zeozeozeo/catppuccin-egui.git", branch = "egui-0.27" }
eframe = { version = "0.27", features = ["persistence"] }
egui_commonmark = { git = "https://github.com/lampsitter/egui_commonmark.git", features = ["better_syntax_highlighting"] }
env_logger = "0.11.3"
flowync = { version = "5.1.0", features = ["compact"] }
log = "0.4.21"
ollama-rs = { git = "https://github.com/pepperoni21/ollama-rs.git", features = ["rustls", "stream"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
egui-modal = "0.3.6"
tts = "0.26.0"
parking_lot = "0.12.1"
bytesize = "1.3.0"
timeago = { version = "0.4.2", default-features = false, features = ["chrono"] }
chrono = "0.4"
egui_virtual_list = "0.3.0"
serde = { version = "1", features = ["derive"] }
egui_dnd = "0.8.0"
